package com.kingyon.newslib.greendao.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kingyon.newslib.greendao.entities.ColumnEntity;

import com.kingyon.newslib.greendao.entities.ColumnEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig columnEntityDaoConfig;

    private final ColumnEntityDao columnEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        columnEntityDaoConfig = daoConfigMap.get(ColumnEntityDao.class).clone();
        columnEntityDaoConfig.initIdentityScope(type);

        columnEntityDao = new ColumnEntityDao(columnEntityDaoConfig, this);

        registerDao(ColumnEntity.class, columnEntityDao);
    }
    
    public void clear() {
        columnEntityDaoConfig.getIdentityScope().clear();
    }

    public ColumnEntityDao getColumnEntityDao() {
        return columnEntityDao;
    }

}
