package com.kingyon.newslib.greendao.entities;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kingyon.newslib.greendao.entities.ColumnEntity;
import com.kingyon.newslib.greendao.entities.NewsEntity;
import com.kingyon.newslib.greendao.entities.AttachmentEntity;
import com.kingyon.newslib.greendao.entities.SocialEntity;

import com.kingyon.newslib.greendao.entities.ColumnEntityDao;
import com.kingyon.newslib.greendao.entities.NewsEntityDao;
import com.kingyon.newslib.greendao.entities.AttachmentEntityDao;
import com.kingyon.newslib.greendao.entities.SocialEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig columnEntityDaoConfig;
    private final DaoConfig newsEntityDaoConfig;
    private final DaoConfig attachmentEntityDaoConfig;
    private final DaoConfig socialEntityDaoConfig;

    private final ColumnEntityDao columnEntityDao;
    private final NewsEntityDao newsEntityDao;
    private final AttachmentEntityDao attachmentEntityDao;
    private final SocialEntityDao socialEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        columnEntityDaoConfig = daoConfigMap.get(ColumnEntityDao.class).clone();
        columnEntityDaoConfig.initIdentityScope(type);

        newsEntityDaoConfig = daoConfigMap.get(NewsEntityDao.class).clone();
        newsEntityDaoConfig.initIdentityScope(type);

        attachmentEntityDaoConfig = daoConfigMap.get(AttachmentEntityDao.class).clone();
        attachmentEntityDaoConfig.initIdentityScope(type);

        socialEntityDaoConfig = daoConfigMap.get(SocialEntityDao.class).clone();
        socialEntityDaoConfig.initIdentityScope(type);

        columnEntityDao = new ColumnEntityDao(columnEntityDaoConfig, this);
        newsEntityDao = new NewsEntityDao(newsEntityDaoConfig, this);
        attachmentEntityDao = new AttachmentEntityDao(attachmentEntityDaoConfig, this);
        socialEntityDao = new SocialEntityDao(socialEntityDaoConfig, this);

        registerDao(ColumnEntity.class, columnEntityDao);
        registerDao(NewsEntity.class, newsEntityDao);
        registerDao(AttachmentEntity.class, attachmentEntityDao);
        registerDao(SocialEntity.class, socialEntityDao);
    }
    
    public void clear() {
        columnEntityDaoConfig.getIdentityScope().clear();
        newsEntityDaoConfig.getIdentityScope().clear();
        attachmentEntityDaoConfig.getIdentityScope().clear();
        socialEntityDaoConfig.getIdentityScope().clear();
    }

    public ColumnEntityDao getColumnEntityDao() {
        return columnEntityDao;
    }

    public NewsEntityDao getNewsEntityDao() {
        return newsEntityDao;
    }

    public AttachmentEntityDao getAttachmentEntityDao() {
        return attachmentEntityDao;
    }

    public SocialEntityDao getSocialEntityDao() {
        return socialEntityDao;
    }

}
