package com.kingyon.newslib.greendao.entities;

import android.os.Parcel;
import android.os.Parcelable;
import android.text.TextUtils;

import com.kingyon.newslib.utils.NewsTypeUtil;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NEWS_ENTITY".
 */
public class NewsEntity implements Parcelable {

    private String type;
    private String displayTemplate;
    private String title;
    private String content;
    private String summary;
    private String source;
    private String contentShareUrl;
    private String webUrl;
    private String videoUrl;
    private Long categoryId;
    private Long objectId;
    private Long publishTime;
    private Boolean isPay;

    // KEEP FIELDS - put your custom fields here
    private List<AttachmentEntity> images;
    private AttachmentEntity mainImage;
    private SocialEntity contentSocail;
    // KEEP FIELDS END

    public NewsEntity() {
    }

    public NewsEntity(Long objectId) {
        this.objectId = objectId;
    }

    public NewsEntity(String type, String displayTemplate, String title, String content, String summary, String source, String contentShareUrl, String webUrl, String videoUrl, Long categoryId, Long objectId, Long publishTime, Boolean isPay) {
        this.type = type;
        this.displayTemplate = displayTemplate;
        this.title = title;
        this.content = content;
        this.summary = summary;
        this.source = source;
        this.contentShareUrl = contentShareUrl;
        this.webUrl = webUrl;
        this.videoUrl = videoUrl;
        this.categoryId = categoryId;
        this.objectId = objectId;
        this.publishTime = publishTime;
        this.isPay = isPay;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getDisplayTemplate() {
        return displayTemplate;
    }

    public void setDisplayTemplate(String displayTemplate) {
        this.displayTemplate = displayTemplate;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getContentShareUrl() {
        return contentShareUrl;
    }

    public void setContentShareUrl(String contentShareUrl) {
        this.contentShareUrl = contentShareUrl;
    }

    public String getWebUrl() {
        return webUrl;
    }

    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getObjectId() {
        return objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public Long getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    public Boolean getIsPay() {
        return isPay;
    }

    public void setIsPay(Boolean isPay) {
        this.isPay = isPay;
    }

    // KEEP METHODS - put your custom methods here

    public String getRealType() {
        if (getType() != null && getType().equals("1")) {
            return NewsTypeUtil.MULTI_THREE_ATLAS;
        } else {
            return NewsTypeUtil.SINGLE_TOP;
        }
    }

    public String getRealSource(){
        if(TextUtils.isEmpty(getSource())){
            return "NewsModule";
        }
        return getSource();
    }

    public List<AttachmentEntity> getImages() {
        return images;
    }

    public void setImages(List<AttachmentEntity> images) {
        this.images = images;
    }

    public AttachmentEntity getMainImage() {
        return mainImage;
    }

    public void setMainImage(AttachmentEntity mainImage) {
        this.mainImage = mainImage;
    }

    public SocialEntity getContentSocail() {
        return contentSocail;
    }

    public void setContentSocail(SocialEntity contentSocail) {
        this.contentSocail = contentSocail;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.type);
        dest.writeString(this.displayTemplate);
        dest.writeString(this.title);
        dest.writeString(this.content);
        dest.writeString(this.summary);
        dest.writeString(this.source);
        dest.writeString(this.contentShareUrl);
        dest.writeString(this.webUrl);
        dest.writeString(this.videoUrl);
        dest.writeValue(this.categoryId);
        dest.writeValue(this.objectId);
        dest.writeValue(this.publishTime);
        dest.writeValue(this.isPay);
        dest.writeList(this.images);
        dest.writeParcelable(this.mainImage, flags);
        dest.writeParcelable(this.contentSocail, flags);
    }

    protected NewsEntity(Parcel in) {
        this.type = in.readString();
        this.displayTemplate = in.readString();
        this.title = in.readString();
        this.content = in.readString();
        this.summary = in.readString();
        this.source = in.readString();
        this.contentShareUrl = in.readString();
        this.webUrl = in.readString();
        this.videoUrl = in.readString();
        this.categoryId = (Long) in.readValue(Long.class.getClassLoader());
        this.objectId = (Long) in.readValue(Long.class.getClassLoader());
        this.publishTime = (Long) in.readValue(Long.class.getClassLoader());
        this.isPay = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.images = new ArrayList<AttachmentEntity>();
        in.readList(this.images, AttachmentEntity.class.getClassLoader());
        this.mainImage = in.readParcelable(AttachmentEntity.class.getClassLoader());
        this.contentSocail = in.readParcelable(SocialEntity.class.getClassLoader());
    }

    public static final Parcelable.Creator<NewsEntity> CREATOR = new Parcelable.Creator<NewsEntity>() {
        @Override
        public NewsEntity createFromParcel(Parcel source) {
            return new NewsEntity(source);
        }

        @Override
        public NewsEntity[] newArray(int size) {
            return new NewsEntity[size];
        }
    };
    // KEEP METHODS END

}
