package com.kingyon.newslib.greendao.entities;

import android.os.Parcel;
import android.os.Parcelable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SOCIAL_ENTITY".
 */
public class SocialEntity implements Parcelable {

    private Long objectId;
    private Long newsId;
    private Integer praisedCount;
    private Integer stepedCount;
    private Integer favouratedCount;
    private Integer commentedCount;
    private Boolean allowComment;
    private Boolean allowPraise;
    private Boolean allowStep;
    private Boolean isFavorite;
    private Boolean isPraise;
    private Boolean isStep;
    private Boolean isCommented;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SocialEntity() {
    }

    public SocialEntity(Long objectId) {
        this.objectId = objectId;
    }

    public SocialEntity(Long objectId, Long newsId, Integer praisedCount, Integer stepedCount, Integer favouratedCount, Integer commentedCount, Boolean allowComment, Boolean allowPraise, Boolean allowStep, Boolean isFavorite, Boolean isPraise, Boolean isStep, Boolean isCommented) {
        this.objectId = objectId;
        this.newsId = newsId;
        this.praisedCount = praisedCount;
        this.stepedCount = stepedCount;
        this.favouratedCount = favouratedCount;
        this.commentedCount = commentedCount;
        this.allowComment = allowComment;
        this.allowPraise = allowPraise;
        this.allowStep = allowStep;
        this.isFavorite = isFavorite;
        this.isPraise = isPraise;
        this.isStep = isStep;
        this.isCommented = isCommented;
    }

    public Long getObjectId() {
        return objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public Long getNewsId() {
        return newsId;
    }

    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    public Integer getPraisedCount() {
        return praisedCount;
    }

    public void setPraisedCount(Integer praisedCount) {
        this.praisedCount = praisedCount;
    }

    public Integer getStepedCount() {
        return stepedCount;
    }

    public void setStepedCount(Integer stepedCount) {
        this.stepedCount = stepedCount;
    }

    public Integer getFavouratedCount() {
        return favouratedCount;
    }

    public void setFavouratedCount(Integer favouratedCount) {
        this.favouratedCount = favouratedCount;
    }

    public Integer getCommentedCount() {
        return commentedCount;
    }

    public void setCommentedCount(Integer commentedCount) {
        this.commentedCount = commentedCount;
    }

    public Boolean getAllowComment() {
        return allowComment;
    }

    public void setAllowComment(Boolean allowComment) {
        this.allowComment = allowComment;
    }

    public Boolean getAllowPraise() {
        return allowPraise;
    }

    public void setAllowPraise(Boolean allowPraise) {
        this.allowPraise = allowPraise;
    }

    public Boolean getAllowStep() {
        return allowStep;
    }

    public void setAllowStep(Boolean allowStep) {
        this.allowStep = allowStep;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public Boolean getIsPraise() {
        return isPraise;
    }

    public void setIsPraise(Boolean isPraise) {
        this.isPraise = isPraise;
    }

    public Boolean getIsStep() {
        return isStep;
    }

    public void setIsStep(Boolean isStep) {
        this.isStep = isStep;
    }

    public Boolean getIsCommented() {
        return isCommented;
    }

    public void setIsCommented(Boolean isCommented) {
        this.isCommented = isCommented;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.objectId);
        dest.writeValue(this.praisedCount);
        dest.writeValue(this.stepedCount);
        dest.writeValue(this.favouratedCount);
        dest.writeValue(this.commentedCount);
        dest.writeValue(this.allowComment);
        dest.writeValue(this.allowPraise);
        dest.writeValue(this.allowStep);
        dest.writeValue(this.isFavorite);
        dest.writeValue(this.isPraise);
        dest.writeValue(this.isStep);
        dest.writeValue(this.isCommented);
    }

    protected SocialEntity(Parcel in) {
        this.objectId = (Long) in.readValue(Long.class.getClassLoader());
        this.praisedCount = (Integer) in.readValue(Integer.class.getClassLoader());
        this.stepedCount = (Integer) in.readValue(Integer.class.getClassLoader());
        this.favouratedCount = (Integer) in.readValue(Integer.class.getClassLoader());
        this.commentedCount = (Integer) in.readValue(Integer.class.getClassLoader());
        this.allowComment = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.allowPraise = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.allowStep = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.isFavorite = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.isPraise = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.isStep = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.isCommented = (Boolean) in.readValue(Boolean.class.getClassLoader());
    }

    public static final Parcelable.Creator<SocialEntity> CREATOR = new Parcelable.Creator<SocialEntity>() {
        @Override
        public SocialEntity createFromParcel(Parcel source) {
            return new SocialEntity(source);
        }

        @Override
        public SocialEntity[] newArray(int size) {
            return new SocialEntity[size];
        }
    };
    // KEEP METHODS END

}
